import { Element } from '@/src/core/types';

export interface ElementTypeDef {
  type: string;
  labelKey: string;
  defaultLabel: string;
  category: 'layout' | 'typography' | 'html' | 'media' | 'interaction' | 'form' | 'data';
  categoryLabel: string;
  iconName: string;
  description: string;
  createElement: (customProps?: Record<string, any>) => Element;
}

export const ELEMENT_DEFINITIONS: ElementTypeDef[] = [
  // MISE EN PAGE
  {
    type: 'section',
    labelKey: 'editor.elements.section',
    defaultLabel: 'Section (<section>)',
    category: 'layout',
    categoryLabel: 'Mise en page',
    iconName: 'LayoutTemplate',
    description: 'Grande bande de contenu sémantique (<section>, <header>, <footer>, <nav>, <main>, <article>).',
    createElement: () => ({
      id: `sec-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'section',
      props: { layoutMode: 'auto', direction: 'vertical', gap: 24, tag: 'section' },
      style: {
        desktop: {
          padding: '48px 24px',
          width: '100%',
          maxWidth: '1200px',
          margin: '0 auto',
          backgroundColor: '#FFFFFF',
          borderRadius: '16px',
        },
        tablet: { padding: '32px 16px' },
        mobile: { padding: '20px 12px' },
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'columns',
    labelKey: 'editor.elements.columns',
    defaultLabel: 'Colonnes (2 ou 3)',
    category: 'layout',
    categoryLabel: 'Mise en page',
    iconName: 'Columns3',
    description: 'Disposez vos contenus côte à côte de manière fluide.',
    createElement: () => ({
      id: `cols-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'columns',
      props: { columnsCount: 2, gap: 20 },
      style: {
        desktop: {
          display: 'grid',
          gridTemplateColumns: 'repeat(2, 1fr)',
          gap: '20px',
          width: '100%',
        },
        tablet: { gridTemplateColumns: 'repeat(2, 1fr)' },
        mobile: { gridTemplateColumns: '1fr' },
      },
      children: [
        {
          id: `col-1-${Date.now()}`,
          type: 'box',
          props: { direction: 'vertical', gap: 12, tag: 'div' },
          style: {
            desktop: { padding: '16px', backgroundColor: '#F7F7FA', borderRadius: '12px' },
            tablet: {},
            mobile: {},
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
        {
          id: `col-2-${Date.now()}`,
          type: 'box',
          props: { direction: 'vertical', gap: 12, tag: 'div' },
          style: {
            desktop: { padding: '16px', backgroundColor: '#F7F7FA', borderRadius: '12px' },
            tablet: {},
            mobile: {},
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
      ],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'box',
    labelKey: 'editor.elements.box',
    defaultLabel: 'Cadre / Conteneur (<div>)',
    category: 'layout',
    categoryLabel: 'Mise en page',
    iconName: 'Box',
    description: 'Conteneur flexible (<div>, <article>, <aside>, <figure>) pour regrouper et styler.',
    createElement: () => ({
      id: `box-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'box',
      props: { direction: 'vertical', gap: 16, tag: 'div' },
      style: {
        desktop: {
          padding: '20px',
          backgroundColor: '#FFFFFF',
          borderRadius: '12px',
          border: '1px solid #E6E6EE',
          display: 'flex',
          flexDirection: 'column',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },

  // TYPOGRAPHIE
  {
    type: 'heading',
    labelKey: 'editor.elements.heading',
    defaultLabel: 'Titre (<h1> - <h6>)',
    category: 'typography',
    categoryLabel: 'Typographie',
    iconName: 'Heading',
    description: 'Titre sémantique (H1, H2, H3, H4, H5, H6) pour structurer la hiérarchie du document.',
    createElement: () => ({
      id: `heading-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'heading',
      props: { text: 'Titre remarquable', tag: 'h2' },
      style: {
        desktop: {
          fontSize: '32px',
          fontWeight: '800',
          color: '#1B1B2F',
          lineHeight: '1.25',
          textAlign: 'left',
        },
        tablet: { fontSize: '26px' },
        mobile: { fontSize: '22px' },
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'text',
    labelKey: 'editor.elements.text',
    defaultLabel: 'Paragraphe de texte (<p>)',
    category: 'typography',
    categoryLabel: 'Typographie',
    iconName: 'AlignLeft',
    description: 'Balise de texte (<p>, <span>, <small>, <em>, <strong>, <mark>).',
    createElement: () => ({
      id: `text-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'text',
      props: {
        text: 'Écrivez ici votre texte. Double-cliquez pour modifier directement le contenu sur la page.',
        tag: 'p',
      },
      style: {
        desktop: {
          fontSize: '16px',
          color: '#62627A',
          lineHeight: '1.6',
          textAlign: 'left',
        },
        tablet: { fontSize: '15px' },
        mobile: { fontSize: '14px' },
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'blockquote',
    labelKey: 'editor.elements.blockquote',
    defaultLabel: 'Citation (<blockquote>)',
    category: 'typography',
    categoryLabel: 'Typographie',
    iconName: 'Quote',
    description: 'Balise HTML <blockquote> pour mettre en valeur des citations avec auteur (<cite>).',
    createElement: () => ({
      id: `quote-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'blockquote',
      props: {
        quote: 'La simplicité est la sophistication suprême.',
        author: 'Léonard de Vinci',
      },
      style: {
        desktop: {
          padding: '16px 20px',
          backgroundColor: '#F7F7FA',
          borderLeft: '4px solid #5B5BF0',
          borderRadius: '0 12px 12px 0',
          fontStyle: 'italic',
          color: '#1B1B2F',
          margin: '12px 0',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },

  // BALISES HTML & CODE SPÉCIFIQUE
  {
    type: 'custom_html',
    labelKey: 'editor.elements.custom_html',
    defaultLabel: 'Balise HTML brute (<custom_html>)',
    category: 'html',
    categoryLabel: 'Balises HTML',
    iconName: 'Code',
    description: 'Insérez n’importe quelle balise HTML brute (<canvas>, <svg>, <details>, <marquee>, etc.).',
    createElement: () => ({
      id: `html-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'custom_html',
      props: {
        htmlCode: '<div class="p-4 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 rounded-xl text-white font-bold shadow-lg flex items-center justify-between">\n  <span>✨ Balise HTML personnalisée</span>\n  <span class="px-2.5 py-1 bg-white/20 rounded-lg text-xs backdrop-blur-xs">Live HTML</span>\n</div>',
      },
      style: {
        desktop: {
          width: '100%',
          margin: '8px 0',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'link',
    labelKey: 'editor.elements.link',
    defaultLabel: 'Lien hypertexte (<a>)',
    category: 'html',
    categoryLabel: 'Balises HTML',
    iconName: 'Link2',
    description: 'Balise <a> avec URL cible, texte personnalisable et options de redirection.',
    createElement: () => ({
      id: `link-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'link',
      props: {
        text: 'En savoir plus sur notre offre →',
        href: '#services',
        target: '_self',
      },
      style: {
        desktop: {
          color: '#5B5BF0',
          fontSize: '15px',
          fontWeight: '600',
          textDecoration: 'underline',
          display: 'inline-block',
          cursor: 'pointer',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'divider',
    labelKey: 'editor.elements.divider',
    defaultLabel: 'Séparateur horizontal (<hr>)',
    category: 'html',
    categoryLabel: 'Balises HTML',
    iconName: 'Minus',
    description: 'Balise <hr> stylisée pour séparer élégamment vos sections et paragraphes.',
    createElement: () => ({
      id: `hr-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'divider',
      props: { lineStyle: 'solid' },
      style: {
        desktop: {
          width: '100%',
          height: '2px',
          backgroundColor: '#E6E6EE',
          border: 'none',
          margin: '24px 0',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'code_block',
    labelKey: 'editor.elements.code_block',
    defaultLabel: 'Bloc de code (<pre><code>)',
    category: 'html',
    categoryLabel: 'Balises HTML',
    iconName: 'FileCode',
    description: 'Balises sémantiques <pre><code> pour afficher des extraits de code avec coloration.',
    createElement: () => ({
      id: `code-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'code_block',
      props: {
        code: `// Exemple de balise sémantique en JavaScript\nconst element = document.createElement('article');\nelement.className = 'card-item';\nconsole.log('Balise prête:', element);`,
        language: 'javascript',
      },
      style: {
        desktop: {
          backgroundColor: '#1E1E2E',
          color: '#F4F4F9',
          padding: '16px',
          borderRadius: '12px',
          fontFamily: 'monospace',
          fontSize: '13px',
          lineHeight: '1.5',
          overflowX: 'auto',
          width: '100%',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'table',
    labelKey: 'editor.elements.table',
    defaultLabel: 'Tableau HTML (<table>)',
    category: 'html',
    categoryLabel: 'Balises HTML',
    iconName: 'Table',
    description: 'Balise <table> complète avec <thead>, <tbody>, <tr>, <th> et <td>.',
    createElement: () => ({
      id: `tbl-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'table',
      props: {
        headers: ['Fonctionnalité', 'Standard', 'Pro'],
        rows: [
          ['Balises sémantiques', 'Inclus', 'Inclus'],
          ['Responsive Mobile', 'Inclus', 'Inclus'],
          ['Export ZIP Clean HTML', 'Basique', 'Illimité'],
          ['Support CMS & Logique', '1 Collection', 'Illimité'],
        ],
      },
      style: {
        desktop: {
          width: '100%',
          borderCollapse: 'collapse',
          backgroundColor: '#FFFFFF',
          borderRadius: '12px',
          overflow: 'hidden',
          border: '1px solid #E6E6EE',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'accordion',
    labelKey: 'editor.elements.accordion',
    defaultLabel: 'Accordéon / Détails (<details>)',
    category: 'html',
    categoryLabel: 'Balises HTML',
    iconName: 'ChevronDown',
    description: 'Balises HTML5 natives <details> et <summary> pour menus et FAQ repliables.',
    createElement: () => ({
      id: `acc-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'accordion',
      props: {
        summary: 'Comment fonctionnent les balises sémantiques ?',
        content: 'Les balises HTML (header, section, article, nav, main, footer) indiquent aux moteurs de recherche et aux lecteurs d’écran la structure exacte de votre contenu.',
        isOpenDefault: false,
      },
      style: {
        desktop: {
          width: '100%',
          padding: '16px',
          backgroundColor: '#F7F7FA',
          borderRadius: '12px',
          border: '1px solid #E6E6EE',
          margin: '8px 0',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'audio',
    labelKey: 'editor.elements.audio',
    defaultLabel: 'Lecteur Audio (<audio>)',
    category: 'media',
    categoryLabel: 'Médias',
    iconName: 'Volume2',
    description: 'Balise HTML5 <audio> avec commandes de lecture, boucle et volume.',
    createElement: () => ({
      id: `aud-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'audio',
      props: {
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
        controls: true,
        autoplay: false,
        loop: false,
      },
      style: {
        desktop: {
          width: '100%',
          margin: '12px 0',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'iframe',
    labelKey: 'editor.elements.iframe',
    defaultLabel: 'Intégration Web (<iframe>)',
    category: 'html',
    categoryLabel: 'Balises HTML',
    iconName: 'Globe',
    description: 'Balise <iframe> pour intégrer des pages externes, cartes Google Maps ou widgets.',
    createElement: () => ({
      id: `ifrm-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'iframe',
      props: {
        src: 'https://www.openstreetmap.org/export/embed.html?bbox=2.25%2C48.81%2C2.42%2C48.90&layer=mapnik',
        title: 'Carte interactive intégrée',
      },
      style: {
        desktop: {
          width: '100%',
          height: '320px',
          border: '1px solid #E6E6EE',
          borderRadius: '12px',
          overflow: 'hidden',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },

  // INTERACTION
  {
    type: 'button',
    labelKey: 'editor.elements.button',
    defaultLabel: 'Bouton d’action (<button>)',
    category: 'interaction',
    categoryLabel: 'Interaction',
    iconName: 'MousePointerClick',
    description: 'Bouton interactif déclenchant une action ou ouvrant un lien.',
    createElement: () => ({
      id: `btn-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'button',
      props: { label: 'Cliquez ici', variant: 'primary', linkUrl: '' },
      style: {
        desktop: {
          padding: '12px 24px',
          backgroundColor: '#5B5BF0',
          color: '#FFFFFF',
          fontSize: '14px',
          fontWeight: '600',
          borderRadius: '10px',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: 'pointer',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'icon',
    labelKey: 'editor.elements.icon',
    defaultLabel: 'Icône décorative (<svg>)',
    category: 'interaction',
    categoryLabel: 'Interaction',
    iconName: 'Sparkles',
    description: 'Symbole graphique vectoriel coloré.',
    createElement: () => ({
      id: `icon-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'icon',
      props: { iconName: 'Sparkles', size: 28 },
      style: {
        desktop: {
          color: '#5B5BF0',
          backgroundColor: '#EEF0FE',
          padding: '10px',
          borderRadius: '12px',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'badge',
    labelKey: 'editor.elements.badge',
    defaultLabel: 'Balise / Badge (<span>)',
    category: 'interaction',
    categoryLabel: 'Interaction',
    iconName: 'Tag',
    description: 'Balise ou étiquette sémantique (<span>) pour catégories, statuts ou tags.',
    createElement: () => ({
      id: `badge-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'badge',
      props: {
        text: 'Balise HTML',
        iconName: 'Sparkles',
        variant: 'primary',
      },
      style: {
        desktop: {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          padding: '6px 14px',
          borderRadius: '9999px',
          backgroundColor: '#EEF0FE',
          color: '#5B5BF0',
          fontSize: '12px',
          fontWeight: '700',
          width: 'fit-content',
          border: '1px solid rgba(91, 91, 240, 0.25)',
          boxShadow: '0 2px 8px -2px rgba(91, 91, 240, 0.15)',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },

  // MÉDIAS & FORMES
  {
    type: 'image',
    labelKey: 'editor.elements.image',
    defaultLabel: 'Image / Photo (<img>)',
    category: 'media',
    categoryLabel: 'Médias',
    iconName: 'Image',
    description: 'Balise <img> avec texte alternatif alt pour le référencement naturel (SEO).',
    createElement: () => ({
      id: `img-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'image',
      props: {
        src: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80',
        alt: 'Dégradé créatif moderne',
      },
      style: {
        desktop: {
          width: '100%',
          maxHeight: '340px',
          objectFit: 'cover',
          borderRadius: '14px',
          display: 'block',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'video',
    labelKey: 'editor.elements.video',
    defaultLabel: 'Lecteur Vidéo (<video>)',
    category: 'media',
    categoryLabel: 'Médias',
    iconName: 'Video',
    description: 'Balise <video> HTML5 avec contrôles et poster.',
    createElement: () => ({
      id: `vid-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'video',
      props: {
        videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
        poster: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800&auto=format&fit=crop&q=80',
        autoplay: false,
        controls: true,
      },
      style: {
        desktop: {
          width: '100%',
          aspectRatio: '16/9',
          borderRadius: '14px',
          overflow: 'hidden',
          backgroundColor: '#0F0F17',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'shape',
    labelKey: 'editor.elements.shape',
    defaultLabel: 'Forme géométrique',
    category: 'media',
    categoryLabel: 'Médias',
    iconName: 'Square',
    description: 'Séparateur, badge, pilule ou rectangle d’accentuation.',
    createElement: () => ({
      id: `shp-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'shape',
      props: { shapeType: 'rectangle' },
      style: {
        desktop: {
          width: '100%',
          height: '4px',
          backgroundColor: '#5B5BF0',
          borderRadius: '4px',
          margin: '12px 0',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },

  // FORMULAIRES
  {
    type: 'form',
    labelKey: 'editor.elements.form',
    defaultLabel: 'Formulaire (<form>)',
    category: 'form',
    categoryLabel: 'Formulaires & Données',
    iconName: 'FileText',
    description: 'Balise <form> pour regrouper et envoyer les champs de données.',
    createElement: () => ({
      id: `frm-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'form',
      props: { formName: 'ContactForm' },
      style: {
        desktop: {
          padding: '24px',
          backgroundColor: '#FFFFFF',
          borderRadius: '16px',
          border: '1px solid #E6E6EE',
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          width: '100%',
        },
        tablet: {},
        mobile: {},
      },
      children: [
        {
          id: `inp-nom-${Date.now()}`,
          type: 'input',
          props: { label: 'Votre nom complet', placeholder: 'Ex: Alex Dupont' },
          style: { desktop: { width: '100%' }, tablet: {}, mobile: {} },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
        {
          id: `btn-sub-${Date.now()}`,
          type: 'button',
          props: { label: 'Envoyer', variant: 'primary' },
          style: {
            desktop: {
              padding: '12px',
              backgroundColor: '#5B5BF0',
              color: '#FFFFFF',
              borderRadius: '10px',
              width: '100%',
            },
            tablet: {},
            mobile: {},
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
      ],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'input',
    labelKey: 'editor.elements.input',
    defaultLabel: 'Champ de saisie (<input>)',
    category: 'form',
    categoryLabel: 'Formulaires & Données',
    iconName: 'FormInput',
    description: 'Balise <input> pour la saisie de texte, email ou mot de passe.',
    createElement: () => ({
      id: `inp-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'input',
      props: { label: 'Champ de texte', placeholder: 'Saisissez votre réponse…' },
      style: {
        desktop: { width: '100%' },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'checkbox',
    labelKey: 'editor.elements.checkbox',
    defaultLabel: 'Case à cocher (<input type="checkbox">)',
    category: 'form',
    categoryLabel: 'Formulaires & Données',
    iconName: 'CheckSquare',
    description: 'Case à cocher Oui/Non avec son libellé (<label>).',
    createElement: () => ({
      id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'checkbox',
      props: { label: 'J’accepte les conditions d’utilisation', checked: false },
      style: {
        desktop: {
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          fontSize: '14px',
          color: '#1B1B2F',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    type: 'list',
    labelKey: 'editor.elements.list',
    defaultLabel: 'Liste à puces (<ul><li>)',
    category: 'form',
    categoryLabel: 'Formulaires & Données',
    iconName: 'ListFilter',
    description: 'Balises <ul> et <li> pour listes non-ordonnées.',
    createElement: () => ({
      id: `list-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'list',
      props: {
        items: [
          'Premier point important et convaincant',
          'Deuxième avantage direct pour vos utilisateurs',
          'Troisième bénéfice prêt à l’emploi',
        ],
      },
      style: {
        desktop: {
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
          paddingLeft: '16px',
        },
        tablet: {},
        mobile: {},
      },
      children: [],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },

  // DONNÉES & CMS
  {
    type: 'dynamic_list',
    labelKey: 'editor.elements.dynamic_list',
    defaultLabel: 'Liste dynamique (CMS)',
    category: 'data',
    categoryLabel: 'Données & CMS',
    iconName: 'Database',
    description: 'Répète un modèle de carte pour chaque entrée d’une collection (ex: Produits).',
    createElement: () => ({
      id: `dynlist-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      type: 'dynamic_list',
      props: {
        collectionId: 'col-produits',
        collectionSlug: 'produits',
        layout: 'grid',
        columns: 3,
        limit: 12,
        gap: 24,
      },
      style: {
        desktop: {
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '24px',
          width: '100%',
          padding: '24px 0',
        },
        tablet: {
          gridTemplateColumns: 'repeat(2, 1fr)',
          gap: '16px',
        },
        mobile: {
          gridTemplateColumns: '1fr',
          gap: '16px',
        },
      },
      children: [
        {
          id: `card-template-${Date.now()}`,
          type: 'box',
          props: { layoutMode: 'auto', direction: 'vertical', tag: 'article' },
          style: {
            desktop: {
              backgroundColor: '#FFFFFF',
              borderRadius: '16px',
              border: '1px solid #E6E6EE',
              boxShadow: '0 4px 20px -2px rgba(0,0,0,0.05)',
              overflow: 'hidden',
              display: 'flex',
              flexDirection: 'column',
              transition: 'transform 0.2s ease, box-shadow 0.2s ease',
            },
            tablet: {},
            mobile: {},
          },
          children: [
            {
              id: `card-img-${Date.now()}`,
              type: 'image',
              props: {
                src: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                alt: 'Image du produit',
              },
              bindings: {
                src: 'item.image',
              },
              style: {
                desktop: {
                  width: '100%',
                  height: '200px',
                  objectFit: 'cover',
                },
                tablet: {},
                mobile: {},
              },
              children: [],
              locked: false,
              hidden: false,
            },
            {
              id: `card-body-${Date.now()}`,
              type: 'box',
              props: { layoutMode: 'auto', direction: 'vertical', gap: 8, tag: 'div' },
              style: {
                desktop: {
                  padding: '20px',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '8px',
                },
                tablet: {},
                mobile: {},
              },
              children: [
                {
                  id: `card-header-row-${Date.now()}`,
                  type: 'box',
                  props: { layoutMode: 'auto', tag: 'div' },
                  style: {
                    desktop: {
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      width: '100%',
                    },
                    tablet: {},
                    mobile: {},
                  },
                  children: [
                    {
                      id: `card-cat-${Date.now()}`,
                      type: 'text',
                      props: { text: 'Catégorie', tag: 'span' },
                      bindings: { text: 'item.categorie' },
                      style: {
                        desktop: {
                          fontSize: '11px',
                          fontWeight: '700',
                          textTransform: 'uppercase',
                          color: '#5B5BF0',
                          letterSpacing: '0.05em',
                        },
                        tablet: {},
                        mobile: {},
                      },
                      children: [],
                      locked: false,
                      hidden: false,
                    },
                    {
                      id: `card-price-${Date.now()}`,
                      type: 'text',
                      props: { text: '99 €', tag: 'strong' },
                      bindings: { text: 'item.prix' },
                      style: {
                        desktop: {
                          fontSize: '15px',
                          fontWeight: '800',
                          color: '#1B1B2F',
                        },
                        tablet: {},
                        mobile: {},
                      },
                      children: [],
                      locked: false,
                      hidden: false,
                    },
                  ],
                  locked: false,
                  hidden: false,
                },
                {
                  id: `card-title-${Date.now()}`,
                  type: 'heading',
                  props: { text: 'Nom du produit', tag: 'h3' },
                  bindings: { text: 'item.nom' },
                  style: {
                    desktop: {
                      fontSize: '18px',
                      fontWeight: '700',
                      color: '#1B1B2F',
                      marginTop: '4px',
                    },
                    tablet: {},
                    mobile: {},
                  },
                  children: [],
                  locked: false,
                  hidden: false,
                },
                {
                  id: `card-desc-${Date.now()}`,
                  type: 'text',
                  props: { text: 'Courte description du produit mettant en valeur ses qualités exceptionnelles.', tag: 'p' },
                  bindings: { text: 'item.description' },
                  style: {
                    desktop: {
                      fontSize: '13px',
                      color: '#62627A',
                      lineHeight: '1.5',
                      marginBottom: '8px',
                    },
                    tablet: {},
                    mobile: {},
                  },
                  children: [],
                  locked: false,
                  hidden: false,
                },
                {
                  id: `card-btn-${Date.now()}`,
                  type: 'button',
                  props: { label: 'Découvrir', linkUrl: '#produit' },
                  style: {
                    desktop: {
                      backgroundColor: '#5B5BF0',
                      color: '#FFFFFF',
                      padding: '10px 16px',
                      borderRadius: '10px',
                      fontSize: '13px',
                      fontWeight: '600',
                      textAlign: 'center',
                      cursor: 'pointer',
                      border: 'none',
                      width: '100%',
                    },
                    tablet: {},
                    mobile: {},
                  },
                  children: [],
                  locked: false,
                  hidden: false,
                },
              ],
              locked: false,
              hidden: false,
            },
          ],
          locked: false,
          hidden: false,
        },
      ],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
];

// MODÈLES DE SECTIONS PRÊTS À L'EMPLOI
export interface SectionTemplateDef {
  id: string;
  name: string;
  category: string;
  description: string;
  createSection: () => Element;
}

export const SECTION_TEMPLATES: SectionTemplateDef[] = [
  {
    id: 'sec-hero-centered',
    name: 'Héros & Accroche Centrale (<header>)',
    category: 'Héros',
    description: 'En-tête sémantique <header> avec titre h1 percutant, sous-titre p et bouton a.',
    createSection: () => ({
      id: `sec-hero-${Date.now()}`,
      type: 'section',
      props: { layoutMode: 'auto', direction: 'vertical', gap: 20, tag: 'header' },
      style: {
        desktop: {
          padding: '64px 24px',
          maxWidth: '960px',
          margin: '0 auto',
          textAlign: 'center',
          backgroundColor: '#FFFFFF',
          borderRadius: '20px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        },
        tablet: { padding: '40px 20px' },
        mobile: { padding: '24px 16px' },
      },
      children: [
        {
          id: `h-badge-${Date.now()}`,
          type: 'badge',
          props: { text: '✨ Nouveauté 2026', iconName: 'Sparkles' },
          style: {
            desktop: {
              fontSize: '12px',
              fontWeight: '700',
              color: '#5B5BF0',
              backgroundColor: '#EEF0FE',
              padding: '6px 14px',
              borderRadius: '20px',
              display: 'inline-flex',
            },
            tablet: {},
            mobile: {},
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
        {
          id: `h-title-${Date.now()}`,
          type: 'heading',
          props: { text: 'Créez vos applications avec des balises HTML sémantiques', tag: 'h1' },
          style: {
            desktop: { fontSize: '42px', fontWeight: '800', color: '#1B1B2F', lineHeight: '1.2' },
            tablet: { fontSize: '32px' },
            mobile: { fontSize: '26px' },
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
        {
          id: `h-sub-${Date.now()}`,
          type: 'text',
          props: {
            text: 'Une interface intuitive pensée pour structurer vos sites web dans les règles du standard W3C.',
            tag: 'p',
          },
          style: {
            desktop: { fontSize: '18px', color: '#62627A', maxWidth: '640px' },
            tablet: { fontSize: '16px' },
            mobile: { fontSize: '15px' },
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
        {
          id: `h-btn-${Date.now()}`,
          type: 'button',
          props: { label: 'Démarrer gratuitement', variant: 'primary' },
          style: {
            desktop: {
              padding: '14px 32px',
              backgroundColor: '#5B5BF0',
              color: '#FFFFFF',
              borderRadius: '12px',
              fontSize: '16px',
              fontWeight: '600',
              marginTop: '8px',
            },
            tablet: {},
            mobile: { width: '100%' },
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
      ],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    id: 'sec-features-3col',
    name: '3 Cartes d’Arguments (<article>)',
    category: 'Avantages',
    description: 'Trois fiches sémantiques <article> avec icône, titre et explication.',
    createSection: () => ({
      id: `sec-feat-${Date.now()}`,
      type: 'section',
      props: { layoutMode: 'auto', direction: 'vertical', gap: 32, tag: 'section' },
      style: {
        desktop: { padding: '48px 24px', maxWidth: '1100px', margin: '0 auto' },
        tablet: { padding: '32px 16px' },
        mobile: { padding: '20px 12px' },
      },
      children: [
        {
          id: `feat-head-${Date.now()}`,
          type: 'heading',
          props: { text: 'Pourquoi choisir notre architecture HTML ?', tag: 'h2' },
          style: {
            desktop: { fontSize: '32px', fontWeight: '800', textAlign: 'center', color: '#1B1B2F' },
            tablet: {},
            mobile: {},
          },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
        {
          id: `feat-grid-${Date.now()}`,
          type: 'columns',
          props: { columnsCount: 3, gap: 20 },
          style: {
            desktop: {
              display: 'grid',
              gridTemplateColumns: 'repeat(3, 1fr)',
              gap: '20px',
              width: '100%',
            },
            tablet: { gridTemplateColumns: '1fr' },
            mobile: { gridTemplateColumns: '1fr' },
          },
          children: [
            {
              id: `card-1-${Date.now()}`,
              type: 'box',
              props: { direction: 'vertical', gap: 12, tag: 'article' },
              style: {
                desktop: {
                  padding: '24px',
                  backgroundColor: '#FFFFFF',
                  borderRadius: '16px',
                  border: '1px solid #E6E6EE',
                },
                tablet: {},
                mobile: {},
              },
              children: [
                {
                  id: `icon-1-${Date.now()}`,
                  type: 'icon',
                  props: { iconName: 'Sparkles', size: 24 },
                  style: {
                    desktop: {
                      color: '#5B5BF0',
                      backgroundColor: '#EEF0FE',
                      padding: '8px',
                      borderRadius: '10px',
                      display: 'inline-flex',
                    },
                    tablet: {},
                    mobile: {},
                  },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
                {
                  id: `tit-1-${Date.now()}`,
                  type: 'heading',
                  props: { text: '100% Sémantique W3C', tag: 'h3' },
                  style: { desktop: { fontSize: '18px', fontWeight: '700', color: '#1B1B2F' }, tablet: {}, mobile: {} },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
                {
                  id: `desc-1-${Date.now()}`,
                  type: 'text',
                  props: { text: 'Chaque bloc génère des balises HTML valides pour un référencement et une accessibilité parfaits.', tag: 'p' },
                  style: { desktop: { fontSize: '14px', color: '#62627A' }, tablet: {}, mobile: {} },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
              ],
              bindings: {},
              locked: false,
              hidden: false,
            },
            {
              id: `card-2-${Date.now()}`,
              type: 'box',
              props: { direction: 'vertical', gap: 12, tag: 'article' },
              style: {
                desktop: {
                  padding: '24px',
                  backgroundColor: '#FFFFFF',
                  borderRadius: '16px',
                  border: '1px solid #E6E6EE',
                },
                tablet: {},
                mobile: {},
              },
              children: [
                {
                  id: `icon-2-${Date.now()}`,
                  type: 'icon',
                  props: { iconName: 'ShieldCheck', size: 24 },
                  style: {
                    desktop: {
                      color: '#10B981',
                      backgroundColor: '#ECFDF5',
                      padding: '8px',
                      borderRadius: '10px',
                      display: 'inline-flex',
                    },
                    tablet: {},
                    mobile: {},
                  },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
                {
                  id: `tit-2-${Date.now()}`,
                  type: 'heading',
                  props: { text: 'Balises Riches & Précises', tag: 'h3' },
                  style: { desktop: { fontSize: '18px', fontWeight: '700', color: '#1B1B2F' }, tablet: {}, mobile: {} },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
                {
                  id: `desc-2-${Date.now()}`,
                  type: 'text',
                  props: { text: 'Intégrez blockquotes, tableaux, accordéons, code brut et iframes sans contrainte.', tag: 'p' },
                  style: { desktop: { fontSize: '14px', color: '#62627A' }, tablet: {}, mobile: {} },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
              ],
              bindings: {},
              locked: false,
              hidden: false,
            },
            {
              id: `card-3-${Date.now()}`,
              type: 'box',
              props: { direction: 'vertical', gap: 12, tag: 'article' },
              style: {
                desktop: {
                  padding: '24px',
                  backgroundColor: '#FFFFFF',
                  borderRadius: '16px',
                  border: '1px solid #E6E6EE',
                },
                tablet: {},
                mobile: {},
              },
              children: [
                {
                  id: `icon-3-${Date.now()}`,
                  type: 'icon',
                  props: { iconName: 'Zap', size: 24 },
                  style: {
                    desktop: {
                      color: '#F59E0B',
                      backgroundColor: '#FEF3C7',
                      padding: '8px',
                      borderRadius: '10px',
                      display: 'inline-flex',
                    },
                    tablet: {},
                    mobile: {},
                  },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
                {
                  id: `tit-3-${Date.now()}`,
                  type: 'heading',
                  props: { text: 'Export Propre en 1 Clic', tag: 'h3' },
                  style: { desktop: { fontSize: '18px', fontWeight: '700', color: '#1B1B2F' }, tablet: {}, mobile: {} },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
                {
                  id: `desc-3-${Date.now()}`,
                  type: 'text',
                  props: { text: 'Téléchargez une archive ZIP contenant du HTML/CSS/JS pur prêt pour Vercel ou Netlify.', tag: 'p' },
                  style: { desktop: { fontSize: '14px', color: '#62627A' }, tablet: {}, mobile: {} },
                  children: [],
                  bindings: {},
                  locked: false,
                  hidden: false,
                },
              ],
              bindings: {},
              locked: false,
              hidden: false,
            },
          ],
          bindings: {},
          locked: false,
          hidden: false,
        },
      ],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
  {
    id: 'sec-footer',
    name: 'Pied de page épuré (<footer>)',
    category: 'Pied de page',
    description: 'Balise sémantique <footer> avec copyright et mentions.',
    createSection: () => ({
      id: `sec-ft-${Date.now()}`,
      type: 'section',
      props: { layoutMode: 'auto', direction: 'vertical', gap: 16, tag: 'footer' },
      style: {
        desktop: {
          padding: '32px 24px',
          maxWidth: '1200px',
          margin: '40px auto 0',
          borderTop: '1px solid #E6E6EE',
          textAlign: 'center',
        },
        tablet: {},
        mobile: {},
      },
      children: [
        {
          id: `ft-txt-${Date.now()}`,
          type: 'text',
          props: { text: '© 2026 Atelier Sans Code — Tous droits réservés.', tag: 'small' },
          style: { desktop: { fontSize: '13px', color: '#8E8EA6' }, tablet: {}, mobile: {} },
          children: [],
          bindings: {},
          locked: false,
          hidden: false,
        },
      ],
      bindings: {},
      locked: false,
      hidden: false,
    }),
  },
];

// BIBLIOTHÈQUE D'IMAGES LIBRES
export interface StockPhoto {
  id: string;
  url: string;
  title: string;
  category: string;
}

export const STOCK_PHOTOS: StockPhoto[] = [
  {
    id: 'img-1',
    title: 'Dégradé Géométrique Violet & Cyan',
    category: 'Abstrait',
    url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'img-2',
    title: 'Espace de Travail Moderne Minimaliste',
    category: 'Bureau',
    url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'img-3',
    title: 'Ondes Dynamiques Bleues',
    category: 'Abstrait',
    url: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'img-4',
    title: 'Collaboration d’Équipe Créative',
    category: 'Humain',
    url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'img-5',
    title: 'Nature & Montagnes Brumeuses',
    category: 'Nature',
    url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'img-6',
    title: 'Architecture Urbaine Futuriste',
    category: 'Design',
    url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
  },
];
